server:
  port: 9003
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/payment_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: PAYMENT-SERVICE
